version: 0.2

env:
  variables:
    NODE_VERSION: "12"
    NODE_ENV: "production"
    NODE_BUILD_PATH: "/app"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - BUILD_MESSAGE=$(git log -1 --pretty=%B 2> /dev/null || echo "Unknown Change")
      - BUILD_NAME=$(jq -r '.name' < meta.json)
      - BUILD_VERSION=$(jq -r '.version' < meta.json)
      - S3_BUCKET=${BUILD_NAME-"wearesho-site"}
      - S3_URI=s3://${S3_BUCKET}

  pre_build:
    commands:
      - docker run --rm -w ${NODE_BUILD_PATH} -v $PWD:${NODE_BUILD_PATH} node:${NODE_VERSION-12}-slim npm i --production --no-audit --loglevel error

  build:
    commands:
      - docker run --rm -w ${NODE_BUILD_PATH} -v $PWD:${NODE_BUILD_PATH} -e NODE_ENV node:${NODE_VERSION-12}-slim npm run build

  post_build:
    commands:
      - aws s3 sync ./web ${S3_URI} --delete
    finally:
      - ([ "$CODEBUILD_BUILD_SUCCEEDING" == "1" ] && (jq ". + {\"bucketUri\":\"$S3_URI\"}" meta.json) || (jq '. + {"failed":true}' meta.json)) > deploy.json
      - |
        if [ -d ".git" ]; then
          DEPLOY_INFO=$(jq ". + {\"comment\":\"$(git log -1 --pretty=%B 2> /dev/null || echo "Unknown Change")\"}" deploy.json)
          echo $DEPLOY_INFO > deploy.json
        fi;

artifacts:
  files:
    - deploy.json
